### ISSUE TITLE
forcedBindings: uris and bnodes

### ISSUE THREAD

**Issue by fr4ncidir** [arces-wot/W3C-Recommendation-Drafts#7]
Let's consider the following example:
```yaml
MYQUERY:
   sparql: select * where {?a rdf:type ?b}
   forcedBindings:
      a:
         type: uri
         value: ""
```
in some situations, the type is a priori not defined: might be uri or bnode, for instance.
What we do in such situations?
